version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/ymaps
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-
      - run:
          name: Nodejs Version
          command: node --version
      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile
      - run:
          name: Build
          command: yarn build
      - run:
          name: Check prettier
          command: yarn prettier-check
      - run:
          name: Test
          command: yarn test
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
